solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Models/ErrorViewModel.cs
namespace SistemaBoleto.AplicacionWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class ClientesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaBoleto.AplicacionWeb.Models;
using System.Diagnostics;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Perfil()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/IdaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class IdaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/NegocioController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class NegocioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/PagosController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class PagosController : Controller
    {
        public IActionResult NuevoPago()
        {
            return View();
        }

        public IActionResult HistorialPago()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/ReportePagosController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class ReportePagosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/ReporteReservaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class ReporteReservaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/ReporteVentaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class ReporteVentaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/ReservaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class ReservaController : Controller
    {
        public IActionResult NuevaReserva()
        {
            return View();
        }
        public IActionResult HistorialReserva()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/RetornoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class RetornoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class UsuariosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;

namespace SistemaBoleto.AplicacionWeb.Controllers
{
    public class VentaController : Controller
    {
        public IActionResult NuevaVenta()
        {
            return View();
        }

        public IActionResult HistorialVenta()
        {
            return View();
        }
    }
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Views/Clientes/Index.cshtml
@{
    ViewData["Title"] = "Clientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Estilos{
    <!-- ============================================================
        =ESTILOS PARA ESTA PAGINA
        ===============================================================-->
    <link rel="stylesheet" href="~/vendor/datatables/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/vendor/datatables/extensiones/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="~/vendor/datatables/extensiones/css/buttons.dataTables.min.css">
}

<div class="card shadow mb-4">
    <div class="card-header py-3 bg-second-primary">
        <h6 class="m-0 font-weight-bold text-white">Lista de Clientes</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-3">
                <button class="btn btn-success" data-toggle="modal" data-target="#modalData"><i class="fas fa-user-plus"></i> Nuevo Usuario</button>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered" id="tbdata" cellspacing="0" style="width:100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Foto</th>
                            <th>Nombre</th>
                            <th>Correo</th>
                            <th>Telefono</th>
                            <th>Rol</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td><img style="height:60px ;" src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300" class="rounded mx-auto d-block" /></td>
                            <td>Tiger Nixon</td>
                            <td>System Architect</td>
                            <td>Edinburgh</td>
                            <td>61</td>
                            <td><span class="badge badge-info">Activo</span></td>
                            <td>
                                <button class="btn btn-primary btn-sm">
                                    <i class="fas fa-pencil-alt"></i>
                                </button>
                                <button class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td><img style="height:60px ;" src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300" class="rounded mx-auto d-block" /></td>
                            <td>Garrett Winters</td>
                            <td>Accountant</td>
                            <td>Tokyo</td>
                            <td>63</td>
                            <td><span class="badge badge-danger">No Activo</span></td>
                            <td>
                                <button class="btn btn-primary btn-sm">
                                    <i class="fas fa-pencil-alt"></i>
                                </button>
                                <button class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--  Modal-->
<div class="modal fade" id="modalData" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6>Detalle Usuario</h6>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" value="0" id="txtId">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="txtNombre">Nombre</label>
                                    <input type="text" class="form-control form-control-sm input-validar" id="txtNombre" name="Nombre">
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="txtCorreo">Correo</label>
                                    <input type="email" class="form-control form-control-sm input-validar" id="txtCorreo" name="Correo">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="txtTelefono">Telefono</label>
                                    <input type="text" class="form-control form-control-sm input-validar" id="txtTelefono" name="Telefono">
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="cboRol">Rol</label>
                                    <select class="form-control form-control-sm" id="cboRol">
                                        <option value="1">Administrador</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="cboEstado">Estado</label>
                                    <select class="form-control form-control-sm" id="cboEstado">
                                        <option value="1">Activo</option>
                                        <option value="0">No Activo</option>
                                    </select>
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="txtFoto">Foto</label>
                                    <input class="form-control-file" type="file" id="txtFoto" />
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <img id="imgUsuario" style="max-width:200px;" src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300" class="rounded mx-auto d-block" alt="Foto usuario">
                        </div>

                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary btn-sm" type="button" id="btnGuardar">Guardar</button>
                <button class="btn btn-danger btn-sm" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <!-- ============================================================
    =SCRIPTS PARA ESTA PAGINA
    ===============================================================-->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>
                 ~/
    <script src="~/vendor/datatables/extensiones/js/dataTables.responsive.min.js"></script>
                 ~/
    <script src="~/vendor/datatables/extensiones/js/dataTables.buttons.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/jszip.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/buttons.html5.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/buttons.print.min.js"></script>

    <!-- SOLO ES DE EJEMPLO - IGNORAR -->
    <script src="~/js/vistas/datatables-demo.js"></script>
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Views/Ida/Index.cshtml
@{
    ViewData["Title"] = "Ida";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Estilos{
    <!-- ============================================================
    =ESTILOS PARA ESTA PAGINA
    ===============================================================-->
    <link rel="stylesheet" href="~/vendor/datatables/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/vendor/datatables/extensiones/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="~/vendor/datatables/extensiones/css/buttons.dataTables.min.css">
}

<div class="card shadow mb-4">
    <div class="card-header py-3 bg-second-primary">
        <h6 class="m-0 font-weight-bold text-white">Lista de Ida</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-3">
                <button class="btn btn-success" data-toggle="modal" data-target="#modalData"><i class="fas fa-plus-circle"></i> Nueva Ruta</button>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered" id="tbdata" cellspacing="0" style="width:100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Descripcion</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Descripcion 1</td>
                            <td><span class="badge badge-info">Activo</span></td>
                            <td>
                                <button class="btn btn-primary btn-sm">
                                    <i class="fas fa-pencil-alt"></i>
                                </button>
                                <button class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Descripcion 2</td>
                            <td><span class="badge badge-danger">No Activo</span></td>
                            <td>
                                <button class="btn btn-primary btn-sm">
                                    <i class="fas fa-pencil-alt"></i>
                                </button>
                                <button class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--  Modal-->
<div class="modal fade" id="modalData" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6>Detalle Ida</h6>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" value="0" id="txtId">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="txtDescripcion">Descripcion</label>
                                    <input type="text" class="form-control form-control-sm" id="txtDescripcion">
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="cboEstado">Estado</label>
                                    <select class="form-control form-control-sm" id="cboEstado">
                                        <option value="1">Activo</option>
                                        <option value="0">No Activo</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary btn-sm" type="button" id="btnGuardar">Guardar</button>
                <button class="btn btn-danger btn-sm" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <!-- ============================================================
    =SCRIPTS PARA ESTA PAGINA
    ===============================================================-->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>
                 ~/
    <script src="~/vendor/datatables/extensiones/js/dataTables.responsive.min.js"></script>
                 ~/
    <script src="~/vendor/datatables/extensiones/js/dataTables.buttons.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/jszip.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/buttons.html5.min.js"></script>
    <script src="~/vendor/datatables/extensiones/js/buttons.print.min.js"></script>

    <!-- SOLO ES DE EJEMPLO - IGNORAR -->
    <script src="~/js/vistas/datatables-demo.js"></script>
}

solucionSistemaBoletos/SistemaBoleto.AplicacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mi Tienda - @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MI TIENDA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","DashBoard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Nav Item - Administración Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administración</span>
                </a>
                <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Usuarios")">Usuarios</a>
                        <a class="collapse-item" href="@Url.Action("Index","Negocio")">Negocio</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Administración Collapse Rutas -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseRutas">
                    <i class="fas fa-fw fa-bus-alt"></i>
                    <span>Rutas</span>
                </a>
                <div id="collapseRutas" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","Ida")">Ida</a>
                        <a class="collapse-item" href="@Url.Action("Index","Retorno")">Retorno</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Inventario Collapse Cliente -->

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Clientes")">
                    <i class="fas fa-fw fa-user-check"></i>
                    <span>Clientes</span>
                </a>
            </li>

            <!-- Nav Item - Venta Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVenta">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Ventas</span>
                </a>
                <div id="collapseVenta" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("NuevaVenta","Venta")">Nueva Venta</a>
                        <a class="collapse-item" href="@Url.Action("HistorialVenta","Venta")">Historial Venta</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Venta Collapse Reserva -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReserva">
                    <i class="fas fa-fw fa-user-clock"></i>
                    <span>Reserva</span>
                </a>
                <div id="collapseReserva" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("NuevaReserva","Reserva")">Nueva Reserva</a>
                        <a class="collapse-item" href="@Url.Action("HistorialReserva","Reserva")">Historial Reserva</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Venta Collapse Pago -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePago">
                    <i class="fas fa-fw fa-dollar-sign"></i>
                    <span>Planilla Pagos</span>
                </a>
                <div id="collapsePago" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("NuevoPago","Pagos")">Nuevo Pago</a>
                        <a class="collapse-item" href="@Url.Action("HistorialPago","Pagos")">Historial Pago</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Reportes Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseReportes">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Reportes</span>
                </a>
                <div id="collapseReportes" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("index","ReporteVenta")">Reporte de Ventas</a>
                        <a class="collapse-item" href="@Url.Action("index","ReportePagos")">Reporte de Pago</a>
                        <a class="collapse-item" href="@Url.Action("index","ReporteReserva")">Reporte de Reserva</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("Perfil","Home")">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>